language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: jocheda-project1-travis
	on: master
	skip_cleanup: true
	api_key:
		secure: o8dVA+Fy3/jWuJBI64ls5hHTVt31Nf1ZZDbgbYfywecW6tYtXArJUccX3kKng8XzCbvISMH/ionipRiKwYIckPDVNBTgLfnEqhUJzknmj8vkA9CU6v4uRJZGyCFFsXKa5JuR/ugYxHTAtrPHS3NJ0S5ljBYkagaPQjCwatQkbcL/tpW21a4S6W1Vh4Lkjksu38Nc86sK/j2fldSsDR8ZNS1GD5svyg4TDW3vLh73xnVZzUmsAlrT2R1zBJ1dHtlSuTiBqqdUU/7a3l41Bh7iaj0Ro3XYCgfn4fBVtxb3e5gqAGBQ2XgrBYOOBijlNl+NDRZR61QP5nnxgeKDmP09PzGUgvvDPbMt1BP6EPXIb08FMuS74J20Mn/fnGR8VKjeb90Ran0NS9Cyhj3NPdGdr9OBJZEMJeqYUBeKzOz2XS4C1F0hPlmdPfrVj7yBm7D865klSsEG7Q67KfHpyFow4NN4K2gZ4O6xyuZaMhaPtc9mBERPZRiCtM0MFFPDUqX3eNBKwKTSItcqlznAhuQ6ZzqktLGUj6vto3ew/hsuJ6rAIfCdTTFVsIk+B8EbwW9X6JXe2XfIopaMatADFhzBLf7ixttZUZbVaCLf6DqCPQ12xDqutJFkRwoqvNHxHReUSr8Dx2E5rUSdtmn3MDRgafIu5mRz2ns9rUx1ORC8Y6g=

